version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: tareas-db
    environment:
      MYSQL_ROOT_PASSWORD: Lopezpedro529
      MYSQL_DATABASE: tareas
    ports:
      - "3307:3306" 
    volumes:
      - db_data:/var/lib/mysql
      - ./tareas.sql:/docker-entrypoint-initdb.d/init.sql 

  backend:
    build: ./backend
    container_name: tareas-backend
    ports:
      - "3001:3001" 
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=Lopezpedro529
      - DB_NAME=tareas
      - PORT=3001 
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: tareas-frontend
    ports:
      - "3000:80" 
    depends_on:
      - backend

volumes:
  db_data: