name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Descargar cÃ³digo
      uses: actions/checkout@v3

    - name: Login en Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Construir y Subir Backend
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/tareas-backend:latest

    - name: Construir y Subir Frontend
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/tareas-frontend:latest

  deploy-to-server:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Desplegar en DigitalOcean
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: root
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /etc/dokploy/compose/final-compose-0kmde2/code

          docker compose pull

          docker rm -f prod-db || true
          docker rm -f prod-backend || true
          docker rm -f prod-frontend || true

          docker compose up -d

          # --- TRUCO DE ORO PARA LA DEMO ---
          # Esperamos a que MySQL termine de iniciar (tarda unos segundos)
          echo "ðŸ˜´ Esperando 20 segundos a que la Base de Datos despierte..."
          sleep 20

          # Reiniciamos el backend para forzar la reconexiÃ³n exitosa
          echo "ðŸ”„ Reiniciando Backend para conectar con la BD..."
          docker restart prod-backend